Article.create( title: "HP", Modelo: "Pavilion V",Procesador: "Intel I5", RAM: "8 GB", Precio: "700")
Article.create( title: "Asus", Modelo: "G7",Procesador: "AMD A6",RAM: "6",Precio: "600")
Article.create( title: "Toshiba", Modelo: "Satellite",Procesador: "Intel I3", RAM: "4 GB", Precio: "400")
Article.create( title: "Dell", Modelo: "Premium",Procesador: "AMD A4",RAM: "6",Precio: "550")
Article.create( title: "Acer", Modelo: "Aspite I",Procesador: "Intel I3", RAM: "4 GB", Precio: "499")